# Generated by Django 4.1.3 on 2022-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=30)),
                ('familais', models.CharField(max_length=30)),
                ('yoshi', models.IntegerField()),
            ],
        ),
    ]
